"""Added new fields in common data

Revision ID: 2ab829780254
Revises: b33ed290175e
Create Date: 2026-02-06 13:28:22.780896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab829780254'
down_revision = 'b33ed290175e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('services', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('price_as_rial', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('deposit_type', sa.String(length=64), nullable=True))
    op.add_column('services', sa.Column('deposit_amount', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'is_active')
    op.drop_column('services', 'deposit_amount')
    op.drop_column('services', 'deposit_type')
    op.drop_column('services', 'price_as_rial')
    op.drop_column('services', 'description')
    op.drop_column('operators', 'is_active')
    # ### end Alembic commands ###
