"""Added base tables

Revision ID: 393482a5c614
Revises: 
Create Date: 2026-01-04 10:44:18.069406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '393482a5c614'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_log',
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_key',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_key_access',
    sa.Column('api_key_id', sa.String(length=64), nullable=False),
    sa.Column('api_tag_id', sa.String(length=64), nullable=True),
    sa.Column('api_id', sa.String(length=64), nullable=True),
    sa.Column('methods', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_tags',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apis',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('methods', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_meta_data',
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('producer_user_id', sa.String(length=64), nullable=True),
    sa.Column('controller_user_id', sa.String(length=64), nullable=True),
    sa.Column('confirmer_user_id', sa.String(length=64), nullable=True),
    sa.Column('approver_user_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_meta_data_file_id'), 'file_meta_data', ['file_id'], unique=True)
    op.create_table('files',
    sa.Column('folder_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('access_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folder_access',
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('folder_id', sa.String(length=64), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('accesses', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('parent_folder_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('service_type', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_change_log',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=64), nullable=False),
    sa.Column('last_fields', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('new_fields', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_field',
    sa.Column('form_id', sa.String(length=64), nullable=False),
    sa.Column('field_type', sa.String(length=64), nullable=False),
    sa.Column('attachment_files', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_field_choice',
    sa.Column('field_id', sa.String(length=64), nullable=False),
    sa.Column('attachment_files', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_instance',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=64), nullable=True),
    sa.Column('usage_type', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_instance_assignment',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('form_instance_id', sa.String(length=64), nullable=False),
    sa.Column('release_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_instance_assignment_user',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('form_instance_assignment_id', sa.String(length=64), nullable=False),
    sa.Column('assigned_from_role_id', sa.String(length=64), nullable=True),
    sa.Column('user_form_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_activity',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expire_timestamp', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('agent', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('login_refresh_token_index', 'login_activity', ['refresh_token'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('login_user_id_and_timestamp_index', 'login_activity', ['user_id', 'expire_timestamp'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('permissions',
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('sub_module', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('en_first_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('en_last_name', sa.String(length=256), nullable=True),
    sa.Column('father_name', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('birth_date', sa.String(length=32), nullable=True),
    sa.Column('national_code', sa.String(length=32), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('phone_number_partial_unique_index', 'profiles', ['phone_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('request_log',
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('process_time', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=64), nullable=True),
    sa.Column('client', sa.Text(), nullable=True),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_headers', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('permission_id', sa.String(length=64), nullable=False),
    sa.Column('had_access_to_all', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('role_permission_permission_index', 'role_permissions', ['permission_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('role_permission_role_index', 'role_permissions', ['role_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('roles',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('show_in_site', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staffs',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user_id_partial_unique_index', 'staffs', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('user_form',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_form_change_log',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_form_id', sa.String(length=64), nullable=False),
    sa.Column('last_answers', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('new_answers', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_form_field_answer',
    sa.Column('user_form_id', sa.String(length=64), nullable=False),
    sa.Column('form_field_id', sa.String(length=64), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('attachment_files', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('permission_id', sa.String(length=64), nullable=False),
    sa.Column('had_access_to_all', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user_role_user_id_index', 'user_roles', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=1028), nullable=True),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('avatar', sa.String(length=64), nullable=True),
    sa.Column('verification_code', sa.String(length=6), nullable=True),
    sa.Column('verification_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('has_completed_profile', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('profile_and_group_conditional_partial_unique_index', 'users', ['profile_id', 'group'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('username_unique_index', 'users', ['username'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND username IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username_unique_index', table_name='users', postgresql_where=sa.text('deleted_at IS NULL AND username IS NOT NULL'))
    op.drop_index('profile_and_group_conditional_partial_unique_index', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_index('user_role_user_id_index', table_name='user_roles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('user_roles')
    op.drop_table('user_permissions')
    op.drop_table('user_form_field_answer')
    op.drop_table('user_form_change_log')
    op.drop_table('user_form')
    op.drop_index('user_id_partial_unique_index', table_name='staffs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('staffs')
    op.drop_table('roles')
    op.drop_index('role_permission_role_index', table_name='role_permissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('role_permission_permission_index', table_name='role_permissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('role_permissions')
    op.drop_table('request_log')
    op.drop_index('phone_number_partial_unique_index', table_name='profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('profiles')
    op.drop_table('permissions')
    op.drop_index('login_user_id_and_timestamp_index', table_name='login_activity', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('login_refresh_token_index', table_name='login_activity', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('login_activity')
    op.drop_table('form_instance_assignment_user')
    op.drop_table('form_instance_assignment')
    op.drop_table('form_instance')
    op.drop_table('form_field_choice')
    op.drop_table('form_field')
    op.drop_table('form_change_log')
    op.drop_table('form')
    op.drop_table('folders')
    op.drop_table('folder_access')
    op.drop_table('files')
    op.drop_index(op.f('ix_file_meta_data_file_id'), table_name='file_meta_data')
    op.drop_table('file_meta_data')
    op.drop_table('apis')
    op.drop_table('api_tags')
    op.drop_table('api_key_access')
    op.drop_table('api_key')
    op.drop_table('api_call_log')
    # ### end Alembic commands ###
