"""Added operator_times table

Revision ID: 3a74a544382c
Revises: 8d57759c8ffb
Create Date: 2026-02-05 11:55:33.394984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a74a544382c'
down_revision = '8d57759c8ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_times',
    sa.Column('operator_id', sa.String(length=64), nullable=True),
    sa.Column('from_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('to_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operator_times')
    # ### end Alembic commands ###
