"""add cancel fields in appointments and appointment_items

Revision ID: 886220f2f588
Revises: 2ab829780254
Create Date: 2026-02-09 17:28:31.118755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886220f2f588'
down_revision = '2ab829780254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_items', sa.Column('is_cancelled', sa.Boolean(), nullable=True))
    op.add_column('appointments', sa.Column('is_cancelled', sa.Boolean(), nullable=True))
    op.add_column('appointments', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('appointments', sa.Column('cancelled_by_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'cancelled_by_id')
    op.drop_column('appointments', 'cancelled_at')
    op.drop_column('appointments', 'is_cancelled')
    op.drop_column('appointment_items', 'is_cancelled')
    # ### end Alembic commands ###
