"""Added base tables

Revision ID: 8d57759c8ffb
Revises: 
Create Date: 2026-02-01 14:10:22.823510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d57759c8ffb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_meta_data',
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('producer_user_id', sa.String(length=64), nullable=True),
    sa.Column('controller_user_id', sa.String(length=64), nullable=True),
    sa.Column('confirmer_user_id', sa.String(length=64), nullable=True),
    sa.Column('approver_user_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_meta_data_file_id'), 'file_meta_data', ['file_id'], unique=True)
    op.create_table('files',
    sa.Column('folder_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('access_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folder_access',
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('folder_id', sa.String(length=64), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('accesses', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('parent_folder_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_activity',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expire_timestamp', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('agent', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('login_refresh_token_index', 'login_activity', ['refresh_token'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('login_user_id_and_timestamp_index', 'login_activity', ['user_id', 'expire_timestamp'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('main_services',
    sa.Column('name', sa.String(length=1028), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators',
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=1028), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('sub_module', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('en_first_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('en_last_name', sa.String(length=256), nullable=True),
    sa.Column('father_name', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('birth_date', sa.String(length=32), nullable=True),
    sa.Column('national_code', sa.String(length=32), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('phone_number_partial_unique_index', 'profiles', ['phone_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('permission_id', sa.String(length=64), nullable=False),
    sa.Column('had_access_to_all', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('role_permission_permission_index', 'role_permissions', ['permission_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('role_permission_role_index', 'role_permissions', ['role_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('roles',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('show_in_site', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('main_service_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=1028), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staffs',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user_id_partial_unique_index', 'staffs', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('user_permissions',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('permission_id', sa.String(length=64), nullable=False),
    sa.Column('had_access_to_all', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user_role_user_id_index', 'user_roles', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=1028), nullable=True),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('avatar', sa.String(length=64), nullable=True),
    sa.Column('verification_code', sa.String(length=6), nullable=True),
    sa.Column('verification_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('has_completed_profile', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('profile_and_group_conditional_partial_unique_index', 'users', ['profile_id', 'group'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('username_unique_index', 'users', ['username'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND username IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username_unique_index', table_name='users', postgresql_where=sa.text('deleted_at IS NULL AND username IS NOT NULL'))
    op.drop_index('profile_and_group_conditional_partial_unique_index', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_index('user_role_user_id_index', table_name='user_roles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('user_roles')
    op.drop_table('user_permissions')
    op.drop_index('user_id_partial_unique_index', table_name='staffs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('staffs')
    op.drop_table('services')
    op.drop_table('roles')
    op.drop_index('role_permission_role_index', table_name='role_permissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('role_permission_permission_index', table_name='role_permissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('role_permissions')
    op.drop_index('phone_number_partial_unique_index', table_name='profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('profiles')
    op.drop_table('permissions')
    op.drop_table('operators')
    op.drop_table('main_services')
    op.drop_index('login_user_id_and_timestamp_index', table_name='login_activity', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('login_refresh_token_index', table_name='login_activity', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('login_activity')
    op.drop_table('folders')
    op.drop_table('folder_access')
    op.drop_table('files')
    op.drop_index(op.f('ix_file_meta_data_file_id'), table_name='file_meta_data')
    op.drop_table('file_meta_data')
    # ### end Alembic commands ###
