from enum import Enum


class ApiCalLogTypeEnum(str, Enum):
    THIRD_PARTY_ISSUE = "THIRD_PARTY_ISSUE"
    BODY_ISSUE = "BODY_ISSUE"
    ELECTRONIC_DEVICES_ISSUE = "ELECTRONIC_DEVICES_ISSUE"
    INDIVIDUAL_INCIDENT_ISSUE = "INDIVIDUAL_INCIDENT_ISSUE"
    FIRE_ISSUE = "FIRE_ISSUE"
    MEDICAL_RESPONSIBILITY_ISSUE = "MEDICAL_RESPONSIBILITY_ISSUE"
    HEALTH_ISSUE = "HEALTH_ISSUE"
    THIRD_PARTY_CLAIM = "THIRD_PARTY_CLAIM"
    BODY_CLAIM = "BODY_CLAIM"