

from enum import Enum


class ErrorCodeEnum(str, Enum):
    ACCESS_DENIED = 'ACCESS_DENIED'
    CONFLICT_WITH_CART = 'CONFLICT_WITH_CART'
    INVALID_CART = 'INVALID_CART'
    CONFLICT_WITH_OTHER_TIMES = 'CONFLICT_WITH_OTHER_TIMES'
    EMPTY_APPOINTMENT = 'EMPTY_APPOINTMENT'
    EMPTY_CART = 'EMPTY_CART'
