from enum import Enum


class AuthenticationErrorCodeEnum(str, Enum):
    INVALID_CREDENTIALS_PROVIDED = 'INVALID_CREDENTIALS_PROVIDED'
    EXPIRED_CREDENTIALS_PROVIDED = 'EXPIRED_CREDENTIALS_PROVIDED'
    MISSING_XACCESS_DATA_HEADER = 'MISSING_XACCESS_DATA_HEADER'
    INVALID_TOKEN = 'MISSING_XTOKEN_HEADER'
    CAN_NOT_USE_REFRESH_TOKEN_FOR_THIS_ROUTE = 'CAN_NOT_USE_REFRESH_TOKEN_FOR_THIS_ROUTE'
    BLOCKED_TOKEN = 'BLOCKED_TOKEN'
    DONT_HAVE_ACCESS_TO_API = 'DONT_HAVE_ACCESS_TO_API'
