from enum import Enum


class FileErrorCodeEnum(str, Enum):
    FILE_IS_PRIVATE = 'FILE_IS_PRIVATE'
    FILE_IS_LOCAL = 'FILE_IS_LOCAL'
    FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED'
    FOLDER_FAILED_TO_DELETE = 'FOLDER_FAILED_TO_DELETE'
    ACCESS_NOT_FOUND = 'ACCESS_NOT_FOUND'
    FILE_NOT_FOR_USER = 'FILE_NOT_FOR_USER'
    FOLDER_NOT_FOR_USER = 'FOLDER_NOT_FOR_USER'

