from enum import Enum


class UserServiceErrorCodeEnum(str, Enum):
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS'
    ERROR_ON_UPDATE_OF_USER = 'ERROR_ON_UPDATE_OF_USER'
    INVALID_TIMESTAMP = 'INVALID_TIMESTAMP'
    INVALID_VERIFICATION_CODE_PROVIDED = 'INVALID_VERIFICATION_CODE_PROVIDED'
    EXPIRED_VERIFICATION_CODE_PROVIDED = 'EXPIRED_VERIFICATION_CODE_PROVIDED'
    PASSWORD_DONT_MATCH = 'PASSWORD_DONT_MATCH'
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    PROFILE_IS_ALREADY_VERIFIED = 'PROFILE_IS_ALREADY_VERIFIED'
    TOKEN_HAS_BEEN_SENT_ALREADY = 'TOKEN_HAS_BEEN_SENT_ALREADY'
    INVALID_CREDENTIAL_PROVIDED = 'INVALID_CREDENTIAL_PROVIDED'
    INVALID_CAPTCHA_PROVIDED = 'INVALID_CAPTCHA_PROVIDED'
    USER_NOT_ACTIVE = 'USER_NOT_ACTIVE'
