from enum import Enum


class RepositoryErrorCodeEnum(str, Enum):
    ENTITY_ALREADY_EXISTS = 'ENTITY_ALREADY_EXISTS',
    ERROR_ON_UPDATING_ENTITY = 'ERROR_ON_UPDATING_ENTITY'
    ERROR_ON_DELETING_ENTITY = 'ERROR_ON_DELETING_ENTITY'
    ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND'
    ERROR_ON_BATCH_INSERT = 'ERROR_ON_BATCH_INSERT'
    ERROR_ON_BATCH_UPDATE = 'ERROR_ON_BATCH_UPDATE'

