acceptable_mime_types:
  # Images
  - image/jpeg
  - image/png
  - image/gif
  - image/bmp
  - image/tiff
  - image/webp
  - image/svg+xml

  # Documents
  - application/pdf
  - application/msword  # .doc
  - application/vnd.openxmlformats-officedocument.wordprocessingml.document  # .docx
  - application/vnd.ms-excel  # .xls
  - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet  # .xlsx
  - application/vnd.ms-powerpoint  # .ppt
  - application/vnd.openxmlformats-officedocument.presentationml.presentation  # .pptx
  - application/rtf  # .rtf
  - text/plain  # .txt
  - application/epub+zip  # .epub
  - application/vnd.oasis.opendocument.text  # .odt
  - application/vnd.oasis.opendocument.spreadsheet  # .ods
  - application/x-iwork-pages-sffpages  # .pages

  # Videos
  - video/mp4
  - video/x-msvideo  # .avi
  - video/x-matroska  # .mkv
  - video/webm
  - video/quicktime  # .mov
  - video/x-flv  # .flv
  - video/mpeg  # .mpeg, .mpg

  # Audio
  - audio/mpeg  # .mp3
  - audio/ogg
  - audio/wav
  - audio/x-wav
  - audio/aac
  - audio/flac
  - audio/webm
  - audio/mp4

  # Archives
  - application/zip
  - application/x-tar
  - application/gzip  # .gz
  - application/x-7z-compressed  # .7z
  - application/x-rar-compressed  # .rar
  - application/x-bzip2  # .bz2
  - application/x-zip-compressed  # alternate .zip type
